### ISSUE TITLE
Add switch for network config.

### ISSUE THREAD

**Issue by robert-zaremba** [alpha-fi/nearswap-ui#14]
It should have one of the following name:
* mainnet
* testnet
* guildnet

**Comment by amityadav0** [comment]
![msg](https://user-images.githubusercontent.com/26249903/99903867-30a62c00-2ced-11eb-84f1-abd6481e6c6a.png)

This message was coming from ethereum connection.

For NEAR connection, we don't have wallet like metamask, so we are switching networks from config.
EX:
```
case 'production':
  case 'mainnet':
    return {
      networkId: 'mainnet',
      nodeUrl: 'https://rpc.mainnet.near.org',
      contractName: CONTRACT_NAME,
      walletUrl: 'https://wallet.near.org',
      helperUrl: 'https://helper.mainnet.near.org',
      explorerUrl: 'https://explorer.mainnet.near.org',
    }
  case 'development':
  case 'testnet':
    return {
      networkId: 'testnet',
      nodeUrl: 'https://rpc.testnet.near.org',
      contractName: CONTRACT_NAME,
      walletUrl: 'https://wallet.testnet.near.org',
      helperUrl: 'https://helper.testnet.near.org',
      explorerUrl: 'https://explorer.testnet.near.org',
    }
  case 'betanet':
    return {
      networkId: 'betanet',
      nodeUrl: 'https://rpc.betanet.near.org',
      contractName: CONTRACT_NAME,
      walletUrl: 'https://wallet.betanet.near.org',
      helperUrl: 'https://helper.betanet.near.org',
      explorerUrl: 'https://explorer.betanet.near.org',
    }
```
Is it related to this or this task is about something else ?

**Comment by robert-zaremba** [comment]
For the moment we want to have a switch based on a config (.env, or some other loaded config). We should be able to easily change the network.
The config must provide all links you have above + smart-contract address (eg: in mainnet it will be a different address, then in testnet).

**Comment by robert-zaremba** [comment]
Other option is to have a switch menu somewhere in the app. @jamesondh  - what do you think?
In each case: we need to protect a user for not doing a mistake. The app must use compatible networks all the time:
* Ethereum test net can only be used with one of the Near test nets (testnet, betanet)
* Ethereum main net can only be used with Near main net
* If use switch a network for an incompatible network, we need to switch other networ, or somehow prompt a user to do it. 
* If user didn't switch network, he can't do ANY operation. It've very important - we need to always check it.
